// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmzMwudxSatFh7xDBTSzAjr3-WZj3GCWY',
    appId: '1:41016171375:web:97ca5b61817b8d164aa69a',
    messagingSenderId: '41016171375',
    projectId: 'notes-53039',
    authDomain: 'notes-53039.firebaseapp.com',
    storageBucket: 'notes-53039.appspot.com',
    measurementId: 'G-CSV9H1GEQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCQ1ne7EdnY7qOhySA3rpre8mQ1a5xKfI',
    appId: '1:41016171375:android:41a4cfdeff0b0a5f4aa69a',
    messagingSenderId: '41016171375',
    projectId: 'notes-53039',
    storageBucket: 'notes-53039.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBep3RcyqUhE-JVCMC-Oa4JKnbJjC7OB1w',
    appId: '1:41016171375:ios:3def6c10bdcd9c4a4aa69a',
    messagingSenderId: '41016171375',
    projectId: 'notes-53039',
    storageBucket: 'notes-53039.appspot.com',
    androidClientId: '41016171375-th365flkuj0nrgph4uoeaistjpndloie.apps.googleusercontent.com',
    iosClientId: '41016171375-9b2vqft2ca1n6usj4v26qudv6fhm0nks.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBep3RcyqUhE-JVCMC-Oa4JKnbJjC7OB1w',
    appId: '1:41016171375:ios:3def6c10bdcd9c4a4aa69a',
    messagingSenderId: '41016171375',
    projectId: 'notes-53039',
    storageBucket: 'notes-53039.appspot.com',
    androidClientId: '41016171375-th365flkuj0nrgph4uoeaistjpndloie.apps.googleusercontent.com',
    iosClientId: '41016171375-9b2vqft2ca1n6usj4v26qudv6fhm0nks.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmzMwudxSatFh7xDBTSzAjr3-WZj3GCWY',
    appId: '1:41016171375:web:7445a2f83b30c7994aa69a',
    messagingSenderId: '41016171375',
    projectId: 'notes-53039',
    authDomain: 'notes-53039.firebaseapp.com',
    storageBucket: 'notes-53039.appspot.com',
    measurementId: 'G-YKQG8BGPLV',
  );

}